.gitignore, cmd/batch/delete_expired_plan_candidates/main.go, cmd/cloudfunctions/main.go, cmd/migrate/migrate_place_entity.go, cmd/server/main.go, internal/env/load_env.go, scripts/README.md, scripts/decrypt.sh, scripts/encrypt.sh
- Places APIキーを環境ごとに分けるために、環境ごとの`.env.*.local`を作成し、それを読み込むようにした
```
```
- API呼び出しの利用を環境ごとに管理できるようにするため
※ Places APIの過度な呼び出しを防ぐために、プラン作成は行っていない
```shell
````
```shell
yarn install
yarn dev
```
=> Places APIキーを環境ごとに分ける

graphql/resolver/plan_candidate_query.resolvers.go, internal/domain/services/place/photo.go, internal/domain/services/place/search_nearby_location.go, internal/domain/services/plancandidate/category.go, internal/domain/services/plancandidate/place.go, internal/domain/services/plangen/create.go, internal/domain/services/plangen/create_by_location.go, internal/infrastructure/api/google/places/details.go, internal/infrastructure/api/google/places/nearbysearch.go, internal/infrastructure/api/google/places/opening.go, internal/infrastructure/api/google/places/photos.go, internal/infrastructure/api/google/places/review.go
- Places APIが過度に呼び出されないように以下の修正を行った
|項目|before|after|
|---|---|---|
|場所ごとに取得される画像の数|10|1|
|興味選択時に提示される場所の数|x|3|
|カテゴリごとに例示される場所の数|5|1|
|プラン内に含まれる場所の上限|x|4|
|プランに場所を追加するときに提示する場所の数|x|4|
|プラン作成可能な場所として提示する場所の数|x|4|
```
```
- #303 
- Places APIの過度な呼び出しをしないようにするため
```shell
export BRANCH_PLANNER=feature/reduce_places_api_call
````
```shell
yarn install
yarn dev
```
=> Places APIの呼び出し件数を減らす

doc/google_places_api.md, internal/domain/factory/google_place_detail.go, internal/domain/factory/google_place_photo.go, internal/domain/models/google_place_detail.go, internal/domain/models/google_place_photo.go, internal/domain/services/place/photo.go, internal/domain/services/plangen/create_plan_data.go, internal/infrastructure/api/google/places/photos.go
- Places APIを利用して画像を取得するためには`Nearby Search`や`Place Detail`によって画像のIDを事前に取得する必要がある。
- これまでは、画像を取得する関数のなかでPlaceDetailを呼び出して、その情報をもちいて画像を取得していた。
- これを、PlaceDetailで画像の他に開店時間やレビューを取得する処理と、それを用いて画像を取得する処理に分けた。
- これにより、PlaceDetailが重複して呼ばれることがなくなるようにした
```
```
- Place Detail APIの呼び出しを減らすため
現段階では機能として完成していないのでテストは行わない
=> [Places API呼び出し改善] 画像IDを取得するためにPlaceDetail APIを重複して呼ばないようにする

.github/workflows/deploy_production.yaml, .github/workflows/deploy_staging.yaml, .github/workflows/workflow_deploy.yaml, app.yaml
- Stagingデプロイするときに、Stagingのプロジェクト（poroto-staging）にデプロイされるようにした
- また、Google App Engineの無料枠を利用するため、plannerのProductionデプロイはStagingプロジェクトに対して行う
```
```
- Staging環境にデプロイされていることを確認
```shell
````
```shell
yarn install
yarn dev
```
=> Staging環境にデプロイされるようにする

graphql/factory/place.go, internal/domain/models/category_with_places.go, internal/domain/models/place.go, internal/domain/models/place_in_plan_candidate.go, internal/domain/models/place_test.go, internal/domain/services/plancandidate/places_to_replace.go, internal/infrastructure/firestore/entity/place.go, internal/infrastructure/firestore/entity/plan.go, internal/infrastructure/firestore/entity/plan_in_candidate.go
- PlaceはGooglePlaceが持つ`Review`や`Rating`の情報を持っていた。
- 今回の修正では`Place `に`GooglePlace`を持たせることで、これらのPlaces APIから取得した値をPlaceの値として持たないようにした。
- 今後、porotoにレビューなどのデータがアップロードされた場合はそれらをPlaceのフィールドとしてもたせる
```
```
- Firestoreに保存されるPlaceのスキーマを変更したため、過去のデータを読み込めなくなった
- 過去のデータを利用するためにはマイングレーションが必要
- 今後の修正でPlaceRepositoryをすべてのプランで共通化し、そこに場所の情報が入るため、マイングレーションを行うとしたらそのPRのあと
- （おそらく、コストとメリットを比較してマイングレーションは行わないと予想している）
- `PlaceRepository`として共通の場所の情報を保存するデータベースを作るため
- このPRではデータ構造の変更がわかりやすくなるように、機能としては完成していない状態でPRを出している
- そのためテストをすることはできない。
=> [PlaceRepository] Placeモデルに不要なプロパティを持たせない

internal/domain/services/place/search_nearby_location.go, internal/domain/services/plancandidate/category.go, internal/domain/services/plangen/create_by_location.go
- 特定のカテゴリ（カフェや温泉）に対して、過去に検索された内容を取得し、それが十分あればNearbySearchを行わないように修正した。
```
```
- #321 
- 料金の高いNearbySearchの呼び出し回数を減らすため
```shell
export BRANCH_PLANNER=feature/reuse_nearby_search
````
```shell
yarn install
yarn dev
```
=> 検索結果のキャッシュを利用してNearbySearchを行うカテゴリ数を減らす

internal/infrastructure/firestore/plan_candidate.go
- プラン候補を取得するときに、検索した場所をすべて取得していたのを、プランに含まれる場所だけを取得するように修正した
- また、メタデータ等の読み込み処理を並行に行うことで、取得速度の改善を図った
|before|after|
|---|---|
|689ms|198ms|
```
```
- プラン候補の読み込み速度を改善するため
```shell
export BRANCH_PLANNER=feature/plan_candidate_fetch_minimum_places
````
```shell
yarn install
yarn dev
```
=> プラン候補を取得するときのパフォーマンス改善

graphql/resolver/plan_candidate_mutation.resolvers.go, internal/domain/models/place_test.go, internal/domain/models/plan.go, internal/domain/models/plan_test.go, internal/domain/repository/plan_candidate.go, internal/domain/services/plancandidate/auto_reorder_places.go, internal/infrastructure/firestore/entity/plan_candidate.go, internal/infrastructure/firestore/entity/plan_in_candidate.go, internal/infrastructure/firestore/entity/plan_in_candidate_test.go, internal/infrastructure/firestore/plan_candidate.go, internal/infrastructure/mock/plan_candidate.go
- 作成されたプランに含まれる場所を、移動が最小になるように並び替える処理を作成した
|並び替え後の経路|
|---|
|![image](https://github.com/poroto-app/planner/assets/55840281/ecf5cf0f-ef0d-447e-aeb2-4804c74545b1)|
```
```
- 編集機能で経路を気にせず追加した場所を、自動的に並び替えられるようにするため
```shell
export BRANCH_PLANNER=feature/place_auto_reorder
````
```shell
yarn install
yarn dev
```
=> 移動経路が最短になるように並び替えられるようにする

internal/domain/factory/google_place.go, internal/domain/factory/google_place_photo.go, internal/domain/models/google_place.go, internal/domain/models/google_place_photo.go, internal/domain/services/place/search_nearby_location.go, internal/domain/services/plancandidate/place.go, internal/infrastructure/api/google/places/details.go, internal/infrastructure/api/google/places/nearbysearch.go, internal/infrastructure/api/google/places/places.go, internal/infrastructure/api/google/places/types.go, internal/infrastructure/firestore/entity/google_place.go, internal/infrastructure/firestore/place.go
- Place Detailの呼び出しをしなくても良いようにするため、Nearby Searchで取得した画像の情報が保存されるようにした。
- また、Nearby Searchで取れる情報はなるべくキャッシュするために住所の情報も取得するようにした
```
```
- Place Detailの呼び出し回数を減らすため（そのための準備）
=> NearbySearchで取得した画像や住所の情報が保存されるようにする

internal/domain/services/place/photo.go, internal/domain/services/place/place_detail.go, internal/domain/services/plancandidate/add_place.go, internal/domain/services/plancandidate/category.go, internal/domain/services/plancandidate/place.go, internal/domain/services/plancandidate/places_to_add.go, internal/domain/services/plancandidate/places_to_replace.go, internal/domain/services/plangen/create.go, internal/domain/services/plangen/create_plan_data.go, internal/infrastructure/api/google/places/photos.go
- Place Detailの呼び出し回数を減らすための修正
- Nearby Searchから取得した情報だけから写真を取得できるようにした
- これにより、写真取得のためにPlaceDetailを呼ぶ必要がなくなった
**プラン作成終了までのPlaces APIの呼び出し回数**
|before|after|
|---|---|
|50|22|
```txt
go run cmd/server/main.go &> log.txt
cat log.txt | grep  "PlacesApi" | wc 
```
```
```
- #344 
- Place Detailの呼び出し回数を減らすため
```shell
export BRANCH_PLANNER=feature/remove_place_detail_call
````
```shell
yarn install
yarn dev
```
=> 写真取得のためにPlaceDetailが呼ばれないようにする

internal/domain/factory/google_place.go, internal/domain/factory/google_place_photo.go, internal/domain/models/google_place.go, internal/domain/models/google_place_photo.go, internal/domain/services/place/photo.go, internal/domain/services/place/place_detail.go, internal/domain/services/place/search_nearby_location.go, internal/domain/services/plancandidate/add_place.go, internal/domain/services/plancandidate/category.go, internal/domain/services/plancandidate/place.go, internal/domain/services/plancandidate/places_to_add.go, internal/domain/services/plancandidate/places_to_replace.go, internal/domain/services/plangen/create.go, internal/domain/services/plangen/create_plan_data.go, internal/infrastructure/api/google/places/details.go, internal/infrastructure/api/google/places/nearbysearch.go, internal/infrastructure/api/google/places/photos.go, internal/infrastructure/api/google/places/places.go, internal/infrastructure/api/google/places/types.go, internal/infrastructure/firestore/entity/google_place.go, internal/infrastructure/firestore/place.go
- キャッシュデータを利用するとき、特定のカテゴリに属している場所の数が一定以上いたときに、Nearby Searchを行わない機能の修正
- この閾値の設定をカテゴリごとに行うようにした
```
```
- #344 
- #345 
- 飲食店はなるべく多くの場所が利用できたほうが良いが、ショッピングモールは場所の数が少ないため、もっと少なくていいなどの指定をできるようにするため
```shell
export BRANCH_PLANNER=feature/search_condition_per_category
````
```shell
yarn install
yarn dev
```
=> カテゴリごとに最低場所数を指定する

graphql/resolver/plan_candidate_query.resolvers.go, internal/domain/models/place.go, internal/domain/models/place_test.go, internal/domain/services/placefilter/filter_by_has_photo.go, internal/domain/services/placefilter/filter_by_has_photo_test.go, internal/domain/services/plancandidate/places_to_add.go, internal/domain/services/plancandidate/places_to_replace.go, internal/domain/services/plangen/select_base_place.go
- before
- 写真がないために、porotoで表示するときにフィルタされ表示されない
- 選択した場所と同じカテゴリの場所だけが表示される
- after:
- 写真が取得できる場所だけをフィルタリングすることで、なるべく表示されるようにする
- ランダム性を入れることで、同じ場所ばかりが表示されることを避ける
- 選択した場所と同じカテゴリの場所と別のカテゴリの場所が同じ数だけ表示されるようにする
```
```
- #345 
- #346 
- 場所を入れ替えるときにより良い場所が見つけやすくなるようにするため
```shell
export BRANCH_PLANNER=feature/improve_places_to_replace
````
```shell
export BRANCH_POROTO=feature/places_to_replace
yarn install
yarn dev
```
=> 場所を入れ替えるときに適切に場所が選択されるようにした

internal/domain/services/place/photo.go, internal/domain/services/place/search_nearby_location.go, internal/domain/services/plan/save.go, internal/domain/utils/logger.go, internal/infrastructure/api/google/places/nearbysearch.go, internal/infrastructure/firestore/place.go
- 水族館等の施設の数が少ない場所を検索するときには、広い範囲を検索するように修正した。
- また、「保存された検索結果にN個含まれていたらNearbySearchを行わない」とするときの、距離のフィルタリングもかけられるようにした。
```
```
- 水族館や温泉等のカテゴリの場所が必要に応じて検索されるようにするため
```shell
export BRANCH_PLANNER=feature/search_range
````
```shell
yarn install
yarn dev
```
=> カテゴリ検索時に検索範囲を指定できるようにする

internal/interface/rest/server.go
- サーバが落ちたときに自動リカバリできるようにstaging, production環境ではリリースモードで実行されるようにした
```
```
```
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
- using env:   export GIN_MODE=release
- using code:  gin.SetMode(gin.ReleaseMode)
```
```shell
````
```shell
yarn install
yarn dev
```
=> staging, productionではリリースモードで実行されるようにする

README.md, docker-compose.yaml
- MySQLをDockerを用いて起動するためのファイルを作成
```
```
- FirestoreからMySQLに順次移行を進めていくため
- だれの環境でも環境構築をしやすくするため
```shell
export BRANCH_PLANNER=feature/docker_mysql
````
```shell
yarn install
yarn dev
```
=> Dockerを用いてMySQLを起動できるようにする

.github/workflows/planetscale_create_deploy_request.yaml
- Github ActionsでPlanetScaleのstagingブランチをmainブランチに自動デプロイできるようにした
- （PlanetScaleのstaging環境に行われたマイグレーションをproduction環境にも行われるようにする）
```
```
- #365 
- #363 
- #362 
- #361 
https://github.com/poroto-app/planner/actions/runs/7287643523
=> Github ActionsでPlanetScaleのDeploy Requestが作成されるようにする

internal/interface/graphql/factory/plan.go, internal/interface/graphql/factory/plan_candidate.go, internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/resolver/plan_candidate_mutation.resolvers.go, internal/interface/graphql/resolver/plan_candidate_query.resolvers.go, internal/interface/graphql/schema/plan_candidate_query.graphqls, internal/interface/graphql/schema/plan_candidate_type.graphqls
- 今までCachedPlanCandidateとしていたクエリを`PlanCandidate`とした
- `CachedPlanCandidate`は次のリリースで削除する
```
```
```shell
````
```shell
yarn install
yarn dev
```
=> PlanCandidateを取得するクエリを追加

README.md, db/migrations/20231223065247_add_timestamps_to_users.sql
- ユーザーテーブルにタイムスタンプカラムを追加した
```
```
- Github ActionsでPlanetScaleに対してマイグレーションを自動実行できることを確認するため
```sh
DB_USER=root \
DB_PASSWORD=password \
DB_HOST=localhost:3306 \
DB_NAME=poroto \
goose -dir db/migrations mysql "$DB_USER:$DB_PASSWORD@tcp($DB_HOST)/$DB_NAME?parseTime=true&loc=Asia%2FTokyo" up
DB_USER=root \
DB_PASSWORD=password \
DB_HOST=localhost:3306 \
DB_NAME=poroto \
goose -dir db/migrations mysql "$DB_USER:$DB_PASSWORD@tcp($DB_HOST)/$DB_NAME?parseTime=true&loc=Asia%2FTokyo" down
```
=> [Migration] ユーザーテーブルにタイムスタンプカラムを追加

db/migrations/20231227115353_create_place_table.sql
- Placeテーブルを作成するときに記述してたTRIGGER句がPlanetScaleでは利用できないため削除した
```
```
- PlanetScaleで適切にマイグレーションを実行できるようにするため
```shell
````
```shell
yarn install
yarn dev
```
=> [Migration] Planet scaleで対応していないTRIGGER句を削除

README.md, docker-compose.yaml, docker/Dockerfile.db-setup, docker/docker-compose.yaml
- `docker compose`を用いてDBを起動するときに、自動的にマイグレーションを行うDockerコンテナのイメージをDockerfileから作成するようにした
```
```
- #382 
- 最初にDockerイメージをビルドすることで、2回目以降の`docker compose up`によるセットアップの速度を改善するため
```sh
cd docker
docker compose up
docker compose up
```
```shell
````
```shell
yarn install
yarn dev
```
=> Dockerfileを用いてDBのセットアップを行うDockerイメージをビルドする

db/migrations/20240106073707_add_location_column_to_plan_table.sql, doc/database/er.md, internal/infrastructure/rdb/generated/plans.go, internal/infrastructure/rdb/mock_test.go, internal/infrastructure/rdb/plan.go
- 位置情報を用いて検索できるようにするために、`plan`テーブルに`location`カラムを追加した
```
```
- 近くのプランを検索できるようにするため
```shell
````
```shell
yarn install
yarn dev
```
=> [Migration] プランテーブルに位置情報を表すカラムを追加

internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/resolver/plan_candidate_mutation.resolvers.go, internal/interface/graphql/schema/plan_candidate_mutation.graphqls
- poroto側でPlaceDetailのAPI呼び出しを発生させないために、Google Place IDからプランを作成するMutationを追加した
```
```
- #369 
- #368 
- poroto側でPlaceDetailのAPI呼び出しを発生させないため
```shell
export BRANCH_PLANNER=feature/graphql_create_plan_by_place_id
````
```shell
yarn install
yarn dev
```
=> [スキーマ変更] Google Place ID　からプランを作成するMutationを追加

internal/domain/services/place/place_detail.go, internal/domain/services/plangen/create_by_google_place_id.go, internal/interface/graphql/resolver/plan_candidate_mutation.resolvers.go
- 緯度・経度を指定せずに、Google Place IDからだけでプランを作成するResolver・Serviceの実装を行った
```
```
- #371 
- poroto側でPlaceDetail APIを用いて緯度・経度をしらべないで良いようにするため
```shell
export BRANCH_PLANNER=feature/graphql_create_plan_by_place_id_impl
````
```shell
yarn install
yarn dev
```
=> Google Place IDからプランを作成できるようにする

cmd/server/main.go, internal/infrastructure/rdb/init.go
- SQLBoilerのクエリログをzapを用いて出力するようにした
```
```
- #395 
- ログレベルを調整することで、クエリを確認したいときだけ表示できるようにするため
- すべてのクエリログが出てしまうと、デバッグが難しくなってしまうため
=> SQLBoilerのログをZapで出力する

go.mod, internal/domain/repository/plan.go, internal/domain/services/plan/fetch_all.go, internal/infrastructure/rdb/plan.go, internal/infrastructure/rdb/plan_test.go, internal/infrastructure/rdb/transaction.go, internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/resolver/plan_query.resolvers.go, internal/interface/graphql/schema/plan_query.graphqls
- 今まで暗黙的にporotoで生成していたページトークンをplanner側で生成するようにした
```
```
- #400 
- 複数プランを取得できるようにするため
- TODO: poroto側の対応
```shell
````
```shell
yarn install
yarn dev
```
=> [スキーマ変更] プラン取得時にページトークンを生成するようにする

internal/domain/services/plan/save.go, internal/infrastructure/rdb/factory/plan_place.go, internal/interface/graphql/resolver/plan_candidate_mutation.resolvers.go
- 過去にプランに含まれた場所と同じ場所を保存しようとするとエラーになるのを修正した
```
```
```shell
````
```shell
yarn install
yarn dev
```
=> 過去に保存された場所をプランに含めるとエラーになるのを修正

internal/domain/repository/place.go, internal/domain/services/placesearch/search_nearby_location.go, internal/infrastructure/rdb/place.go, internal/infrastructure/rdb/place_test.go, internal/infrastructure/rdb/query_mods.go
- NearbySearchをする前にキャッシュを確認する処理内で、カテゴリごとに検索範囲を指定している。
- このときにDBに保存されたキャッシュを取得するときに、カテゴリと距離を指定して検索できるようにした
```
```
- 単純に付近にお店がない場合にNearbySearchが走ってしまうため
- 検索範囲を広めに持つことで余分なAPI呼び出しがされないようにした
```shell
export BRANCH_PLANNER=feature/place_repository_find_by_category
````
```shell
yarn install
yarn dev
```
=> 場所のカテゴリで保存された場所を検索できるようにする

internal/domain/services/placefilter/filter_default_ignore.go, internal/domain/services/plangen/create_by_location.go, internal/domain/services/plangen/create_plan_places.go, internal/domain/services/plangen/select_base_place.go, internal/domain/services/plangen/select_base_place_test.go, internal/domain/utils/logger.go, internal/interface/graphql/resolver/plan_candidate_mutation.resolvers.go
- プラン作成のために基準となる３箇所が選択されるが、すべての場所が何らかの条件に合わなくなるとプランができなくなってしまう。
- そこで、基準となる場所を10箇所程度選択し、プランが作成できるまでループするようにした。
```
```
- #409 
- プランが一つしかできない or 一つもできない事態を防ぐため
```shell
export BRANCH_PLANNER=feature/create_plan_base_locations
````
```shell
yarn install
yarn dev
```
=> プランの開始地点となる場所を10箇所ほど選択し、プランが1件も作成できないという現象を減らす

internal/domain/models/plan.go, internal/domain/services/plan/save.go, internal/infrastructure/rdb/factory/plan.go, internal/infrastructure/rdb/factory/plan_candidate.go, internal/infrastructure/rdb/factory/plan_candidate_set.go, internal/infrastructure/rdb/factory/plan_test.go, internal/infrastructure/rdb/factory/user.go, internal/infrastructure/rdb/mock_test.go, internal/infrastructure/rdb/plan.go, internal/infrastructure/rdb/plan_candidate.go, internal/infrastructure/rdb/plan_test.go, internal/infrastructure/rdb/user.go, internal/interface/graphql/factory/plan.go
- プランを作成したユーザーの名前、プロフィール画像を取得できるようにした
```
```
- #414 
- プランの作者の情報を調べられるようにするため
```shell
````
```shell
yarn install
yarn dev
```
=> プラン取得時に作成者のデータを取得できるようにする

internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/schema/place_type.graphqls, internal/interface/graphql/schema/plan_candidate_query.graphqls
- 複数の場所をカテゴリごとにグループ化して表示して表示できるようにスキーマを修正
```
```
- 「もう飲食店を含めなくていいから別の場所を含めたい」というような状況に対応できるようにするため
```shell
export BRANCH_PLANNER=feature/graphql_fetch_places_by_categories
````
```shell
yarn install
yarn dev
```
=> [スキーマ変更]プランに場所を追加するときにカテゴリごとに候補となる場所を閲覧できるようにする

internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/schema/plan_mutation.graphqls
画像投稿Muationの修正
```
```
画像サイズを固定値でなく個々に適切なサイズを指定できるようにするため
```shell
export BRANCH_PLANNER=feature/graphql_modify_upload_photo_mutation
````
```shell
yarn install
yarn dev
```
=> [スキーマ変更]画像投稿Mutationに画像サイズを指定するプロパティを追加

internal/infrastructure/rdb/place.go, internal/infrastructure/rdb/place_test.go, internal/infrastructure/rdb/rdb_main_test.go
- 既存のプレイスに対し関連した写真を`user_id`と`place_id`と紐付けて保存できるようにした
- `photo_url`がまだ保存されていないことを確認するようにした
- `usesr_id`と`place_id`が既存のものであるかを確認するようにした
- 機能の確認testを作成した
- テスト用DBのクリーンアップ関数に該当テーブルを追加した
```
```
```shell
export BRANCH_PLANNER=feature/insert_place_photos_to_rdb
````
```shell
yarn install
yarn dev
```
=> ユーザが撮影した写真をDBに保存できるようにする

internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/resolver/plan_mutation.resolvers.go, internal/interface/graphql/schema/plan_candidate_mutation.graphqls, internal/interface/graphql/schema/plan_mutation.graphqls
- Graphqlスキーマ変更
- プラン候補や保存済みプランで場所に対していいねするときにユーザー情報を付与できるようにした。
```
```
- プラン候補作成中以外でもログインユーザーであれば場所に対していいねできるようにする
- 将来的にいいねした場所からプランを作れるようにするため
```shell
export BRANCH_PLANNER=feature/graphql_like_by_user
````
```shell
yarn install
yarn dev
```
=> [Graphql] ログインユーザーが場所に対していいねできるようにする

internal/domain/repository/place.go, internal/domain/repository/plan_candidate.go, internal/infrastructure/rdb/entities/plan_candidate_set_place_likes.go, internal/infrastructure/rdb/place.go, internal/infrastructure/rdb/place_test.go, internal/infrastructure/rdb/plan_candidate_test.go, internal/infrastructure/rdb/plan_test.go, internal/infrastructure/rdb/rdb_main_test.go
- ユーザーがいいねしたことを`user_like_places`テーブルに保存する処理を実装した
```
```
- #436 
- #435 
```shell
export BRANCH_PLANNER=feature/like_place_by_user_db
````
```shell
yarn install
yarn dev
```
=> ユーザーがいいねしたことをDBに保存する

internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/resolver/plan_mutation.resolvers.go, internal/interface/graphql/resolver/user_query.resolvers.go, internal/interface/graphql/schema/plan_mutation.graphqls, internal/interface/graphql/schema/user_query.graphqls
- いいねをしたときや、プランを表示するときにいいねした場所を取得できるようにする
```
```
```shell
````
```shell
yarn install
yarn dev
```
=> [スキーマ変更] ユーザーがいいねした場所を取得できるようにする

internal/domain/repository/place.go, internal/domain/services/plan/like_place.go, internal/domain/services/user/find_liked_places.go, internal/domain/services/user/service.go, internal/infrastructure/rdb/place.go, internal/infrastructure/rdb/place_test.go, internal/interface/graphql/resolver/plan_mutation.resolvers.go, internal/interface/graphql/resolver/resolver.go, internal/interface/graphql/resolver/user_query.resolvers.go, internal/interface/rest/graphql.go
- プラン内の場所にたいしていいねしたときや、プランを取得したときにユーザーがいいねした場所を取得できるようにした
- また、どこにいいねしたかを確認できるのは本人だけにした
```
```
- #442 
**Postmanでユーザーのログイン状態を再現する方法**
1. porotoでログインを行う
2. ReduxからUserIDを確認する
1. porotoのコードを書き換えて、ログイントークンをコンソールに出力して確認する
https://github.com/poroto-app/poroto/blob/d5f7acbbbf8c3ce7437ed16f361cc6ea4aefd00d/src/view/hooks/useAuth.ts#L25
```ts
console.log("idToken", idToken);
```
1. UserIDを`userId`, ログイントークンを`firebaseAuthToken`に入力する
```shell
export BRANCH_PLANNER=feature/get_user_like_places
````
```shell
yarn install
yarn dev
```
=> ユーザーがいいねした場所を取得できるようにする

internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/resolver/plan_mutation.resolvers.go, internal/interface/graphql/resolver/user_query.resolvers.go, internal/interface/graphql/schema/plan_candidate_query.graphqls
- プランを作成するときに、ログインユーザーの場合、そのユーザーがいいねした場所を取得する必要がある
- そのために、ログイン情報を付け加えられるようにした
```
```
- #443 
```shell
export BRANCH_PLANNER=feature/graphql_plan_candidate_with_user
````
```shell
yarn install
yarn dev
```
=> [Graphql] プラン候補を指定するときにログインユーザーとして取得できるようにする

internal/domain/services/plancandidate/find.go, internal/domain/services/plancandidate/like_to_place.go, internal/interface/graphql/resolver/plan_candidate_mutation.resolvers.go, internal/interface/graphql/resolver/plan_candidate_query.resolvers.go
- プラン作成中は「いいね」をするとプラン候補に結びつくようになっていた
- ログインしている場合は、「いいね」がユーザーに紐づくようにした
```
```
- ログイン状態でプランを作成したときに、適切にいいねができるようにするため
```shell
export BRANCH_PLANNER=feature/plan_candidate_with_user
````
```shell
yarn install
yarn dev
```
=> プラン作成中もログインユーザーとしていいねをできるようにする

internal/domain/models/place_test.go
- 配列をシャッフルするテストで要素数が少ないためにテストが落ちることが頻繁に発生した
- テストのデータ数を3から10に増やすことで、テストが落ちづらくなるようにした
```sh
1 / 3! = 6
1 / 10! = 3628800
```
```
```
- テストが落ちないようにする
```fish
for i in (seq 10)                                                                                                                                                                                
go test -count=1 ./...
end
```
```shell
export BRANCH_PLANNER=feature/fix_shuffle_test
````
```shell
yarn install
yarn dev
```
=> TestShufflePlacesが落ちないようにする

internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/resolver/place_query.resolvers.go, internal/interface/graphql/resolver/plan_candidate_mutation.resolvers.go, internal/interface/graphql/resolver/plan_candidate_query.resolvers.go, internal/interface/graphql/resolver/plan_mutation.resolvers.go, internal/interface/graphql/resolver/plan_query.resolvers.go, internal/interface/graphql/resolver/user_query.resolvers.go, internal/interface/graphql/schema/plan_candidate_query.graphqls
- 追加する場所の候補を提示するときに、基準となる場所を指定できるようにスキーマを変更した
- また、指定した場所からの移動時間も取得できるようにした。
```
```
- 追加しようとした場所から、もっとも良い候補を提示できるようにするため
- どれだけの距離にあるかをわかりやすくするため
```shell
export BRANCH_PLANNER=feature/graphql_add_place_by_selected_place
````
```shell
yarn install
yarn dev
```
=> [スキーマ変更] 追加する場所の候補を提示するときに、基準となる場所を指定できるようにする

README.md, internal/domain/models/place.go, internal/domain/models/transition.go, internal/domain/services/place/places_to_add.go, internal/infrastructure/rdb/plan_candidate.go, internal/interface/graphql/factory/transition.go, internal/interface/graphql/resolver/plan_candidate_query.resolvers.go
- プラン編集画面で追加しようとした場所を基準として、候補となる場所が提示されるように修正した
- また、基準となる場所からの移動時間も取得できるようにした
```
```
- #469 
- プラン作成をより行いやすくするため
```shell
export BRANCH_PLANNER=feature/add_place_by_selected_place
````
```shell
yarn install
yarn dev
```
=> 指定した場所を基準として追加する場所が提案されるようにする

internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/schema/image_type.graphqls
- 画像のアップロードもとを区別できるようにするために、Graphqlのスキーマを変更した
```
```
```shell
export BRANCH_PLANNER=feature/graphql_place_photo_google_or_user
````
```shell
yarn install
yarn dev
```
=> [スキーマ変更]画像がGoogleから取得したものかユーザーによりアップロードされたものかを区別できるようにする

internal/infrastructure/rdb/place.go
- komichiトップページに表示される「いいねした場所」一覧について、最近いいねした場所が先頭に表示されるように修正した
```
```
- close #510
- 直前にいいねした場所からすぐにプランを作れるようにするため
```shell
export BRANCH_PLANNER=feature/sort_like_places
````
```shell
yarn install
yarn dev
```
=> 最近いいねした場所が先頭に表示されるように修正

internal/domain/models/place.go, internal/domain/models/place_test.go, internal/interface/graphql/factory/place.go
- 番地情報等が含まれない大雑把な住所情報を取得できるようにした
```
```
- 大まかな住所を知れるようにするため
```shell
export BRANCH_PLANNER=feature/place_address_shorten
````
```shell
export BRANCH_POROTO=feature/place_with_address
yarn install
yarn dev
```
=> より短い住所データを取得できるようにする

cmd/features/down_size_google_place_photo/main.go, cmd/features/down_size_google_place_photo/main_test.go
- DBに保存された高画質なGoogle Places PhotoのURLを500x500まで低下させるように書き換えるスクリプトを作成
```
```
- close #505
- トップページの読み込み速度を改善するため
```shell
export BRANCH_PLANNER=feature/down_size_google_place_photo
````
```shell
yarn install
yarn dev
```
=> DBに保存されたGoogle Places Photoの画質を下げる

internal/infrastructure/api/google/places/photos.go
- Google Place Photos APIから取得する画像のサイズを 最大 500x500になるように修正した
```
```
- close #506 
- トップページの読み込み速度を改善するため
```shell
export BRANCH_PLANNER=feature/google_place_photo_resolution
````
```shell
yarn install
yarn dev
```
=> Google Places APIから取得する画像サイズを小さくする

internal/domain/services/plancandidate/create_from_saved_plan.go, internal/domain/services/plancandidate/service.go, internal/interface/graphql/resolver/plan_candidate_mutation.resolvers.go, internal/interface/graphql/resolver/plan_mutation.resolvers.go
- すでに保存されているプランをコピーし PlanCnadidateSetを作成するMutationを実装した。
```
```
- close #534 
- モデルコースをベースにプランを作成できるようにするため
```shell
export BRANCH_PLANNER=feature/customize_plan_from_saved_from
````
```shell
yarn install
yarn dev
```
=> すでに保存されているプランをカスタムできるようにする

internal/domain/services/place/places_to_add.go, internal/domain/services/place/places_to_replace.go
- プランカスタムによって作成したときに、追加・関連する場所を提示できない不具合を修正した。
```
```
```shell
export BRANCH_PLANNER=feature/fix_fetch_places_of_customized_plan
````
```shell
export BRANCH_POROTO=feature/customize_plan_from_saved_plan
yarn install
yarn dev
```
=> プラン候補について検索した場所が無い場合に追加・関連した場所が提示できない不具合を修正

gqlgen.yml, internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/resolver/plan_type.resolvers.go, internal/interface/graphql/schema/plan_type.graphqls
- Graphqlスキーマ変更
- プランのプロパティとして、近くのプランを取得できるようにした。
```
```
- #539 
- プラン詳細ページから別のプランを閲覧できるようにするため
```shell
export BRANCH_PLANNER=feature/graphql_neaby_plans
````
```shell
yarn install
yarn dev
```
=> [Graphql] プランの近くのプランを取得できるようにする

internal/interface/graphql/resolver/plan_type.resolvers.go
- 指定されたプランの近くにあるプランを取得するQueryを実装した。
```
```
- #540 
- close #539 
- プラン詳細ページから別のプランを閲覧できるようにするため
```shell
export BRANCH_PLANNER=feature/neaby_plans
````
```shell
yarn install
yarn dev
```
=> プランの近くのプランを取得できるようにする

internal/domain/repository/plan.go, internal/domain/services/plan/fetch_by_location.go, internal/infrastructure/rdb/place.go, internal/infrastructure/rdb/plan.go, internal/infrastructure/rdb/plan_test.go, internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/resolver/plan_query.resolvers.go, internal/interface/graphql/resolver/plan_type.resolvers.go, internal/interface/graphql/schema/plan_query.graphqls
- PlanRepositoryの位置情報に基づいて、プランを取得する処理について、ページング機能やソート機能を削除した。
```
```
```shell
export BRANCH_PLANNER=feature/rdb_neaby_plans
````
```shell
yarn install
yarn dev
```
=> 距離に応じてプランを取得する処理をリファクタ

db/migrations/20240605084012_add_is_place_searched_to_plan_candidate_sets.sql, doc/database/er.md, internal/domain/models/plan_candidate.go, internal/domain/repository/plan_candidate.go, internal/domain/services/place/places_for_plan.go, internal/domain/services/place/places_to_add.go, internal/domain/services/place/places_to_replace.go, internal/domain/services/placesearch/search_nearby_location.go, internal/domain/services/plancandidate/category_nearby.go, internal/domain/services/plangen/create_by_location.go, internal/domain/services/plangen/create_from_place.go, internal/infrastructure/mock/plan_candidate.go, internal/infrastructure/rdb/factory/plan_candidate_set.go, internal/infrastructure/rdb/generated/plan_candidate_sets.go, internal/infrastructure/rdb/plan_candidate.go, internal/infrastructure/rdb/plan_candidate_test.go
- プラン作成時に場所の検索を行ったかという履歴を記録するようにした
- 以前は検索した場所をすべて記録していたが、その代わりに検索を行ったか否かだけを記録するようにした。
**背景**
- #543 の修正により、プラン候補が検索した場所一覧を保存する処理を削除した
- 付近の特定のカテゴリが無い場合に、すでに検索が行われているのに、再度検索が行われてしまうという状況が発生してしまうようになった
- そこで、検索が行われたかどうかという履歴を管理することで、再検索が行われないようにした。
```
```
- #543 
- 不要な再検索が行われないようにするため
```shell
````
```shell
yarn install
yarn dev
```
=> すでに検索を行ったかという履歴を残す

db/migrations/20240608041046_increase_users_photo_url_length.sql, internal/interface/rest/graphql.go
- 以下の２つの原因で新規ユーザー登録ができなくなってしまっていた。
1. Graphqlの認証状態を確認するミドルウェア内で、初回ログイン時に認証ヘッダに登録されたユーザー情報と一致するものがDB上に存在せずエラーとなってしまう
2. 登録されたユーザーのアイコン画像のURLが256文字を超え、DBに登録できない。
これに伴い以下の修正を行った。
```
```
- ユーザー登録を行えるようにするため
```shell
````
```shell
yarn install
yarn dev
```
=> 新規ユーザー登録ができなくなってしまうバグを修正

db/migrations/20240608092636_add_parent_plan_id_to_plan_candidate.sql
- MySQLではALTER TABLEの処理の中で、カラムの追加とカラム制約の追加を同時に行うことができないため、わける変更を行った。
```
```
```shell
````
```shell
yarn install
yarn dev
```
=> MySQL 5.7に合わせてクエリを修正

internal/domain/services/user/update_profile.go, internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/resolver/plan_type.resolvers.go, internal/interface/graphql/resolver/user_mutation.resolvers.go, internal/interface/graphql/schema/user_mutation.graphqls
- ユーザー名・プロフィール画像を更新するためのMutationを作成
```
```
- #556 
- ユーザー情報を更新できるようにするため。
```shell
export BRANCH_PLANNER=feature/graphql_update_user_profile
````
```shell
yarn install
yarn dev
```
=> [スキーマ変更] ユーザーのプロフィールを更新できるようにする

internal/apperrors/errors.go, internal/domain/repository/user.go, internal/domain/services/user/update_profile.go, internal/domain/utils/string.go, internal/domain/utils/string_test.go, internal/infrastructure/rdb/user.go, internal/infrastructure/rdb/user_test.go, internal/interface/graphql/resolver/user_mutation.resolvers.go
- ユーザー名やユーザーのアバター画像を更新できるようにした
```
```
- #557 
- close #556 
**テスト時の注意**
Authenticationタブで、Firestoreから提供される認証トークンを設定する必要がある。
```shell
export BRANCH_PLANNER=feature/update_user_profile
````
```shell
yarn install
yarn dev
```
=> ユーザーのプロフィールを更新できるようにする

.env.development, .env.production, .env.staging, internal/domain/models/category_create_plan.go, internal/domain/services/plangen/create_by_category.go, internal/env/load_env.go, internal/infrastructure/rdb/place.go, internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/resolver/plan_candidate_mutation.resolvers.go, internal/interface/graphql/resolver/plan_candidate_query.resolvers.go, internal/interface/graphql/resolver/user_mutation.resolvers.go, internal/interface/graphql/schema/place_type.graphqls, internal/interface/graphql/schema/plan_candidate_mutation.graphqls, internal/interface/graphql/schema/plan_candidate_query.graphqls
- 場所を指定せずにカテゴリからプランを作成できるようにした
```
```
- #564 
- トップページからカテゴリに基づいてプランを作成できるようにするため
```shell
export BRANCH_PLANNER=feature/create_plan_from_category
````
```shell
yarn install
yarn dev
```
=> カテゴリからプランを作成できるようにする

internal/interface/graphql/generated/generated.go, internal/interface/graphql/model/models_gen.go, internal/interface/graphql/resolver/plan_candidate_mutation.resolvers.go, internal/interface/graphql/resolver/plan_candidate_query.resolvers.go, internal/interface/graphql/resolver/user_mutation.resolvers.go, internal/interface/graphql/schema/place_type.graphqls, internal/interface/graphql/schema/plan_candidate_mutation.graphqls, internal/interface/graphql/schema/plan_candidate_query.graphqls
- プラン作成のためのカテゴリ（温泉や博物館など）を取得できるQueryを追加した。
- カテゴリからプランを作成できるようにMuationを追加した
```
```
- トップページからカテゴリ（気分）に応じてプランを作成できるようにするため
```shell
export BRANCH_PLANNER=feature/graphql_create_plan_from_category
````
```shell
yarn install
yarn dev
```
=> [スキーマ変更] カテゴリからプランを作成できるようにする

internal/domain/models/plan_candidate_meta_data.go, internal/domain/services/plancandidate/save_plans.go, internal/infrastructure/rdb/factory/plan_candidate_set.go, internal/infrastructure/rdb/factory/plan_candidate_set_meta_data.go, internal/infrastructure/rdb/factory/plan_candidate_set_meta_data_create_by_category.go, internal/infrastructure/rdb/mock_test.go, internal/infrastructure/rdb/plan_candidate.go, internal/infrastructure/rdb/plan_candidate_test.go, internal/infrastructure/rdb/rdb_main_test.go, internal/interface/graphql/resolver/plan_candidate_mutation.resolvers.go
- カテゴリからプランを作成したときのカテゴリ、範囲等の情報をRDBに保存・取得できるようにした
```
```
- #571 
- close #572
- #565
- プラン作成後に、最初に指定した条件にマッチする他の場所を提示できるようにするため
```shell
export BRANCH_PLANNER=feature/plan_candidate_set_from_category
````
```shell
yarn install
yarn dev
```
=> カテゴリからプランを作成したときの情報を保存・取得できるようにする

internal/domain/services/place/places_destination_for_plan_candidate.go, internal/interface/graphql/resolver/plan_candidate_query.resolvers.go
- カテゴリからプランを作成したときに、その条件をもとに他の目的地を取得する機能を実装した
```
```
- #574 
- close #573 
- カテゴリからプランを作成したときに、その他の場所から簡単にプランを作成できるようにするため
```shell
export BRANCH_PLANNER=feature/plan_candate_by_category_places
````
```shell
yarn install
yarn dev
```
=> 他の目的地を取得できるようにする

internal/infrastructure/rdb/plan_candidate.go, internal/infrastructure/rdb/plan_candidate_test.go, internal/infrastructure/rdb/util_test.go
- PlanCandidateSetに含まれるPlanCandidateの順番は`SortOrder`プロパティによって制御されている
- 作成済みのPlanCandidateSetにプランを追加するときに、このプロパティが正しく指定されていないため、デタラメな順番でプランが追加されてしまうバグを修正した
```
```
```shell
````
```shell
yarn install
yarn dev
```
=> プランを追加したときに、追加されたプランが一覧の最後に追加されるようにする

db/migrations/20240703091106_create_place_photo_references_table.sql, internal/infrastructure/rdb/generated/place_photo_references.go, internal/infrastructure/rdb/generated/users.go
複数画像を管理するマイグレーションの修正
```
```
マイグレーションファイルの構文修正
```shell
export BRANCH_PLANNER=fix/db_place_photo_references
````
```shell
yarn install
yarn dev
```
=> [Fix] ユーザ投稿の画像を複数の画質で管理できるようにする

cmd/features/script_create_place_photo_references_entities/main.go
- 既存の`placePhotos`データをもとに、新規テーブル`placePhotoReferences`に相当データを生成
```
```
- 既存データに複数画質で管理する方法を適用するため
- `placePhotoReferences`が`placePhotos`のデータをもとに生成されること
->`place_id`と`user_id`が同等であること
- `placePhoto.placePhotoReferenceId`が対応する`placePhotoReference.Id`であること  
```shell
export BRANCH_PLANNER=feature/feature/script_create_place_photo_references_entities
````
```shell
yarn install
yarn dev
```
=> [既存データを反映] ユーザ投稿の画像を複数の画質で管理できるようにする
