.github/dependabot.yaml

- dependabotでライブラリのアップデートをするPRを作成するときに、マイナーバージョンアップデートは無視されるようにした。
```
```
- パッチアップデートを取り入れていると大量にPRが作成されてしまうため

パッチバージョンアップデートを無視する

---

graphql/generated/generated.go
graphql/model/models_gen.go
graphql/resolver/plan_candidate_mutation.resolvers.go
graphql/schema/place_type.graphqls
graphql/schema/plan_candidate_mutation.graphqls
graphql/schema/plan_type.graphqls

プラン候補内プランの指定のプレイスにLikeする機能のためのスキーマ変更
```
```
APIに頼らないporoto独自の情報を集計するため
```shell
export BRANCH_PLANNER=feature/graphql_like_to_place
````
```shell
yarn install
yarn dev
```

[プレイスにLikeする機能][スキーマ変更]プレイスにLikeをする機能

---

internal/domain/models/place.go
internal/domain/models/plan_candidate.go

ドメインモデルにLikeカウンタのプロパティを追加
```
```
Placeに対するLike情報を扱うため
```shell
````
```shell
yarn install
yarn dev
```

[プレイスにLikeする機能] ドメインモデルの修正

---

internal/domain/models/place.go
internal/infrastructure/firestore/entity/place.go
internal/infrastructure/firestore/entity/plan_candidate.go
internal/infrastructure/firestore/plan_candidate.go

PlaceEntityモデルにLikeカウンタプロパティを追加
PlanCandidateEntityのモデル変換関数にLike情報を扱えるよう修正・関数名を修正
```
```
以前のPRは古いdevelopを参照していたため、あらためて作り直した。
```shell
export BRANCH_PLANNER=feature/like_to_place_entity_model
````
```shell
yarn install
yarn dev
```

[プレイスにLikeする機能] Entityモデルおよび関数の修正 

---

graphql/factory/place.go
graphql/factory/plan.go
graphql/generated/generated.go
graphql/model/models_gen.go
graphql/resolver/plan_candidate_mutation.resolvers.go
graphql/resolver/plan_candidate_query.resolvers.go
graphql/schema/plan_candidate_mutation.graphqls
graphql/schema/plan_candidate_query.graphqls
graphql/schema/plan_candidate_type.graphqls
graphql/schema/plan_type.graphqls
internal/domain/services/plancandidate/like_to_place.go
internal/infrastructure/firestore/plan_candidate.go

Mutationから実際にLike機能を実行する処理を作成した
```
```
フロントからLike関数を実行するため
```shell
export BRANCH_PLANNER=feature/like_to_place_service
````
```shell
yarn install
yarn dev
```

[プレイスにLikeする機能] Service&リゾルバの実装

---

.github/actions/deploy_cloud_functions/action.yaml
.github/workflows/deploy_staging.yaml
.github/workflows/workflow_deploy.yaml

```
```
https://github.com/poroto-app/planner/actions/runs/7168587278
```shell
````
```shell
yarn install
yarn dev
```

[Github Actions修正] Cloud FunctionにGen2でデプロイされるようにする

---

.env.development
cmd/feature/mysql_user_repository/main.go
doc/planetscale.md
internal/env/load_env.go

- PlanetScale上のDBに書き込み & マイグレーションをする修正を行った
```
```
- #363 
- #362 
- #361 
1. PlanetScaleにログイン
```
pscale auth login
```
3. ローカル環境から接続できるようにする
```
pscale connect poroto branch_name --port 3309 --org poroto
```
5. シークレットを復元
```
bash scripts/decrypt.sh
```
7. テストコードを実行
```
ENV=staging  go run cmd/feature/mysql_user_repository/main.go
```

PlanetScaleに読み書きされるようにする

---

.github/workflows/planetscale_migrate_staging.yaml
cmd/feature/mysql_user_repository/main.go

- developにマージされたときに、マイグレーションが行われていたらPlanetScaleのStagingブランチに適用するGithub Actionsを作成
```
```
- #366 
- #365
- #363
- #362 
- #361 
- Stagingへのマイグレーション適用を自動化するため
https://github.com/poroto-app/planner/actions/runs/7288780484

[PlanetScale] StagingブランチにマイグレーションがGithub Actionsで実行されるようにする

---

internal/domain/models/category.go
internal/domain/models/category_test.go
internal/domain/models/place_test.go
internal/domain/services/plangen/create.go

- テイクアウトを「ごはん」カテゴリにし、パン屋等のカテゴリを切り出した。
- 遊びに行くプランを考えるときにより適切な粒度になるようにした
```
```
- 遊びに行くプランを考えるときにより適切な粒度になるようにするため
```shell
export BRANCH_PLANNER=feature/remove_takeout_category
````
```shell
yarn install
yarn dev
```

カテゴリの分割を修正

---

internal/domain/utils/int.go
internal/domain/utils/pointer.go
internal/domain/utils/pointer_test.go
internal/domain/utils/string.go
internal/infrastructure/rdb/factory/plan.go
internal/infrastructure/rdb/factory/plan_place.go
internal/infrastructure/rdb/factory/plan_place_test.go
internal/infrastructure/rdb/factory/plan_test.go
internal/infrastructure/rdb/mock_test.go
internal/infrastructure/rdb/plan.go
internal/infrastructure/rdb/plan_candidate_test.go
internal/infrastructure/rdb/plan_test.go
internal/infrastructure/rdb/rdb_main_test.go

- プランをRDBに保存・取得できるようにした
```
```
- RDBに移行するため

PlanRepositoryをRDBで実装

---

internal/infrastructure/rdb/mock_test.go
internal/infrastructure/rdb/plan.go
internal/infrastructure/rdb/plan_test.go

- RDB版PlanRepositoryで距離に応じてプランを検索する機能を実装した
```
```
- RDBに移行するため

距離に応じてプランを検索できるようにする

---

internal/infrastructure/rdb/factory/google_place_type.go
internal/infrastructure/rdb/init.go
internal/infrastructure/rdb/mock_test.go
internal/infrastructure/rdb/plan_candidate.go
internal/infrastructure/rdb/plan_candidate_test.go
internal/infrastructure/rdb/query_mods.go

- プランに紐づく場所のデータを取得するときに、写真が取得できないバグを修正した
```
```
- #396 
```shell
````
```shell
yarn install
yarn dev
```

写真が取得できない不具合を修正

---

doc/database/er.md

place_photosの構造関係をDBのerDiagram図に追加
```
```
今後ユーザが場所に関連した画像を投稿できるよう、
DB上でのデータ構造を明示するため
```shell
export BRANCH_PLANNER=feature/erdiagram_place_photos
````
```shell
yarn install
yarn dev
```

place_photosのerDiagramを追加

---

internal/interface/graphql/resolver/plan_mutation.resolvers.go

- `util`パッケージを利用している箇所でimportができていないバグを修正
```
```
```shell
````
```shell
yarn install
yarn dev
```

utilパッケージをimportできていないエラーを修正

---

internal/infrastructure/rdb/factory/place.go
internal/infrastructure/rdb/place.go
internal/infrastructure/rdb/plan.go
internal/infrastructure/rdb/plan_candidate.go
internal/interface/graphql/resolver/plan_mutation.resolvers.go

Get関数をすべてを取得したあとフィルタリングする処理から、forループ内でそれぞれのPlaceEntityに関連するものだけ取得しそのままfactory関数に引き渡すよう修正
```
```
コードを見やすく、より簡潔にするため
```shell
export BRANCH_PLANNER=feature/get_place_photos_refactor
````
```shell
yarn install
yarn dev
```

[リファクタ]PlacePhotosをRを用いて取得

---

internal/infrastructure/rdb/place_test.go

placeRepository.FindByLocation()の単体テストを作成した
```
```
```shell
export BRANCH_PLANNER=feature/find_by_location_test
````
```shell
yarn install
yarn dev
```

FindByLocationの単体テストを作成

---

.env.production

- ドメイン移管に伴う修正
- CORSの許可等で用いられれるドメイン名をporotoからkomichiに変更
```
```
```shell
````
```shell
yarn install
yarn dev
```

ドメイン名をporotoからkomichiに変更

---

internal/domain/models/category.go

- 公園がプランに含めないようにする設定を削除した
```
```
```shell
export BRANCH_PLANNER=feature/category_park
````
```shell
yarn install
yarn dev
```

公園がプランに含められるようにする

---

internal/domain/services/placesearch/search_nearby_location.go

- プラン作成時に書店が検索されるようにする
```
```
- 書店がプランに含められるようにするため
```shell
export BRANCH_PLANNER=feature/search_bookstore
````
```shell
yarn install
yarn dev
```

書店が検索されるようにする

---

.env.staging

- Staging環境でCORSによるエラーが起きないように設定値を修正した。
```
```
```shell
````
```shell
yarn install
yarn dev
```

Stagingのドメイン名を修正

---

.github/workflows/db_migrate_production.yaml
.github/workflows/db_migrate_staging.yaml
.github/workflows/db_migrate_workflow.yaml

- main, developブランチマージ時に自動的にマイグレーションが実行されるようにした
```
```
- マイグレーション実行を自動化するため
https://github.com/poroto-app/planner/actions/runs/8486932540
https://github.com/poroto-app/planner/actions/runs/8486932538
```shell
````
```shell
yarn install
yarn dev
```

Github ActionsからTiDBのマイグレーションを行う

---

internal/infrastructure/rdb/place.go
internal/interface/graphql/resolver/plan_candidate_mutation.resolvers.go

不要なエラーハンドリング処理の削除
```
```
コードをより明瞭にするため
```shell
export BRANCH_PLANNER=feature/fix_err_handling
````
```shell
yarn install
yarn dev
```

[fix]不要なエラーハンドリング処理の削除

---

internal/domain/models/place.go
internal/domain/models/place_photo.go
internal/domain/models/place_test.go
internal/infrastructure/rdb/factory/place.go
internal/infrastructure/rdb/factory/place_photo.go
internal/interface/graphql/factory/place.go

- 最後にアップロードされた画像が最初に来るように修正した
```
```
- #485 
- ユーザーがアップロードした瞬間に、トップに表示されるようにするため
```shell
export BRANCH_PLANNER=feature/reorder_user_uploaded_photo_first
````
```shell
yarn install
yarn dev
```

画像をアップロードされた日付けが新しい順で並び替える

---

cmd/server/main.go
internal/domain/services/user/find_liked_places.go
internal/interface/graphql/context/user.go
internal/interface/graphql/resolver/user_query.resolvers.go
internal/interface/graphql/resolver/user_type.resolvers.go
internal/interface/rest/graphql.go
internal/interface/rest/server.go

- before：ユーザー情報を取得してから、保存したプラン等を取得
- after: ユーザー情報と同時に保存したプラン等を取得できるようにする
```
```
- close #499 
- トップページのユーザー関連情報の読み込み速度を改善するため
```shell
export BRANCH_PLANNER=feature/authenticated_user
````
```shell
yarn install
yarn dev
```

ログインユーザーの関連情報を一括で取得できるようにする

---

internal/interface/graphql/generated/generated.go
internal/interface/graphql/model/models_gen.go
internal/interface/graphql/resolver/user_mutation.resolvers.go
internal/interface/graphql/schema/place_type.graphqls

- 各場所の住所を取得できるようにした
```
```
- トップページ等で場所一覧を表示するときに、大まかな場所がわかるようにするため
```shell
export BRANCH_PLANNER=feature/graphql_place_address
````
```shell
yarn install
yarn dev
```

[スキーマ変更] 場所の住所を取得できるようにする

---

internal/domain/models/place.go
internal/infrastructure/rdb/factory/place.go
internal/interface/graphql/factory/place.go

- 場所のデータを取得するときに、住所もあわせて取得できるようにした
```
```
- #512 
```shell
export BRANCH_PLANNER=feature/place_address
````
```shell
yarn install
yarn dev
```

場所の住所情報を取得する

---

internal/domain/repository/place.go
internal/domain/services/place/places_recommended.go
internal/infrastructure/rdb/place.go
internal/infrastructure/rdb/place_test.go
internal/infrastructure/rdb/rdb_main_test.go
internal/interface/graphql/resolver/place_query.resolvers.go

- 場所を指定してプランを作成するのにおすすめの場所を取得するGraphql Resolverの実装を行った
```
```
- #523 
- close #521 
```shell
````
```shell
yarn install
yarn dev
```

[WIP] 場所を指定してプランを作成するのにおすすめの場所を取得

---

cmd/features/recommended_places_for_plan/README.md
cmd/features/recommended_places_for_plan/main.go
internal/domain/repository/place.go
internal/domain/services/place/places_recommended.go
internal/infrastructure/rdb/place.go
internal/infrastructure/rdb/place_test.go
internal/infrastructure/rdb/rdb_main_test.go
internal/interface/graphql/resolver/place_query.resolvers.go

- 場所を指定してプランを作成するのにおすすめの場所を取得するGraphql Resolverの実装を行った
```
```
- #525 
- close #521 
**おすすめの場所の追加方法  => `cmd/features/recommended_places_for_plan/README.md`参照**
```shell
````
```shell
yarn install
yarn dev
```

場所を指定してプランを作成するのにおすすめの場所を取得

---

db/migrations/20240703091106_create_place_photo_references_table.sql

- USERカラムの型がVARCHAR（36）であったので、テーブル作成のときの型を合わせた
```
```
- TablePlustでクエリが実行できることを確認
```shell
````
```shell
yarn install
yarn dev
```

USERカラムの型を修正
